version: 2
jobs:
  build:
    working_directory: ~/Amazon_customers
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command:  sudo python -m pip install --user setuptools virtualenv
      - run:
          command: |
             coverage run manage.py test
              coverage report -m