version: 2
jobs:
  build:
    working_directory: ~/Amazon_customers
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command:
            python3 -m venv env
            source ./amazon/bin/activate
            pip install setuptools virtualenv --python=python3
#          sudo chown -R $USER /usr/local/bin/easy_install
      - run:
          command: |
             coverage run manage.py test
              coverage report -m