version: 2
jobs:
  build:
    working_directory: ~/Amazon_customers
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command:
            sudo chown -R $USER /usr/local/bin/easy_install
            source amazon/bin/activate
            sudo pip3 install setuptools virtualenv
      - run:
          command: |
             coverage run manage.py test
              coverage report -m